# Generated by Django 4.2.6 on 2024-01-09 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_user_active_backlogs_user_current_cgpa_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="twelfth_percentage",
            new_name="twelth_percentage",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="twelfth_school_name",
            new_name="twelth_school_name",
        ),
    ]
